/* PROCEDIMIENTO UTILIZADO PARA CONTROLAR EL ACCESO AL PROGRAMA */
CREATE DEFINER=`root`@`localhost` PROCEDURE `SEARCHrec`(
	IN `emp` VARCHAR(10),
	IN `pass` VARCHAR(16)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'PROCEDIMIENTO UTILIZADO PARA CONTROLAR EL ACCESO AL PROGRAMA'
SELECT COUNT(recID) AS isExist
FROM Recepcionista
WHERE (recID LIKE emp) AND (passRec LIKE pass)
