/* 
CREACION DE PROCEDIMIENTOS db_AgenciaInmobiliaria
INTEGRANTES:
- KEVIN ALAN FLORES REYNA - 20660053
- ANGEL DAVID LOPEZ ALVAREZ - 20660062
*/


/* PROCEDIMIENTO UTILIZADO PARA CONTROLAR EL ACCESO AL PROGRAMA */
CREATE DEFINER=`root`@`localhost` PROCEDURE `SEARCHrec`(
	IN `emp` VARCHAR(10),
	IN `pass` VARCHAR(16)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'PROCEDIMIENTO UTILIZADO PARA CONTROLAR EL ACCESO AL PROGRAMA'
SELECT COUNT(recID) AS isExist
FROM Recepcionista
WHERE (recID LIKE emp) AND (passRec LIKE pass);

/* PROCEDIMIENTO UTILIZADO PARA AGREGAR VALORES A LA TABLA PRODUCTOS */
CREATE DEFINER=`root`@`localhost` PROCEDURE `ADDproduct`(
	IN `codProductoP` INT(4),
	IN `nomProductP` VARCHAR(32),
	IN `unidadMedidaP` VARCHAR(4),
	IN `precioP` DECIMAL(7,2),
	IN `stockP` INT(3),
	IN `cantidadUMP` INT(4)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'PROCEDIMIENTO UTILIZADO PARA AGREGAR VALORES A LA TABLA PRODUCTOS'
INSERT INTO Producto (codProducto, nomProduct, unidadMedida, precio, stock, cantidadUM) 
VALUES (codProductoP,nomProductP,unidadMedidaP,precioP,stockP,cantidadUMP);

/* PROCEDIMIENTO UTILIZADO PARA BUSCAR TODOS LOS PRODUCTOS */
CREATE DEFINER=`root`@`localhost` PROCEDURE `SEARCHproduct`(
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'PROCEDIMIENTO UTILIZADO PARA BUSCAR TODOS LOS PRODUCTOS'
SELECT codProducto, nomProduct, precio, stock, unidadMedida, cantidadUM
FROM producto
ORDER BY codProducto ASC;

/* PROCEDIMIENTO UTILIZADO PARA BUSCAR PRODUCTOS DE FORMA AISLADA*/
CREATE DEFINER=`root`@`localhost` PROCEDURE `SEARCHproductUNIQUE`(
	IN `codProductoP` INT(4)
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT 'PROCEDIMIENTO UTILIZADO PARA BUSCAR LOS PRODUCTOS DE FORMA AISLADA'
SELECT codProducto, nomProduct, precio, stock, unidadMedida, cantidadUM
FROM Producto
WHERE (codProducto = codProductoP);
