import java.sql.*;
import javax.swing.JOptionPane;
/*
*   VENTANA QUE SIRVE A MANERA DE MENU PRINCIPAL DEL PROGRAMA
*   INTEGRANTES DEL EQUIPO
*   - Kevin Alan Flores Reyna - 20660053
*   - Angel David Lopez Alvarez - 20660062
*/

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ventana = new javax.swing.JPanel();
        menubar = new javax.swing.JMenuBar();
        menres = new javax.swing.JMenu();
        Resypro = new javax.swing.JMenuItem();
        menadd = new javax.swing.JMenu();
        addhab = new javax.swing.JMenuItem();
        addprod = new javax.swing.JMenuItem();
        addcli = new javax.swing.JMenuItem();
        Usuarios = new javax.swing.JMenu();
        Usu = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenu();
        CerrarS = new javax.swing.JMenuItem();
        CerrarP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(910, 416));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));

        menres.setText("Reservar");

        Resypro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Resypro.setText("Reservas y productos");
        Resypro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResyproActionPerformed(evt);
            }
        });
        menres.add(Resypro);

        menubar.add(menres);

        menadd.setText("Añadir");

        addhab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addhab.setText("Habitación");
        addhab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhabActionPerformed(evt);
            }
        });
        menadd.add(addhab);

        addprod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addprod.setText("Producto");
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });
        menadd.add(addprod);

        addcli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addcli.setText("Cliente");
        addcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcliActionPerformed(evt);
            }
        });
        menadd.add(addcli);

        menubar.add(menadd);

        Usuarios.setText("Configurar");

        Usu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Usu.setText("Usuarios");
        Usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuActionPerformed(evt);
            }
        });
        Usuarios.add(Usu);

        menubar.add(Usuarios);

        Close.setText("Salir");

        CerrarS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CerrarS.setText("Cerrar Sesión");
        CerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSActionPerformed(evt);
            }
        });
        Close.add(CerrarS);

        CerrarP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CerrarP.setText("Carrar Programa");
        CerrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarPActionPerformed(evt);
            }
        });
        Close.add(CerrarP);

        menubar.add(Close);

        setJMenuBar(menubar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcliActionPerformed
        // Codigos necesarios para mostrar la subventana de clientes en la interfaz
        addCliente clientes = new addCliente();
        Ventana.add(clientes);
        clientes.show();
    }//GEN-LAST:event_addcliActionPerformed

    private void UsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuActionPerformed
        // Codigos necesarios para mostrar la subventana de usuarios en la interfaz
        Usuarios usuarios = new Usuarios();
        Ventana.add(usuarios);
        usuarios.show();
    }//GEN-LAST:event_UsuActionPerformed

    private void CerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSActionPerformed
        JOptionPane.showMessageDialog(null, "FINALIZANDO LA SESION ACTUAL","SESION CERRADA", JOptionPane.INFORMATION_MESSAGE);

        // Codigos necesarios para mostrar la ventana de login y cerrar el menu principal
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSActionPerformed

    private void CerrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarPActionPerformed
        System.exit(0);     // Se cierra la ventana y finaliza la ejecucion
    }//GEN-LAST:event_CerrarPActionPerformed

    private void addhabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhabActionPerformed
        // Codigos necesarios para mostrar la subventana de habitaciones en la interfaz
        addHabitacion habitacion = new addHabitacion();
        Ventana.add(habitacion);
        habitacion.show();
    }//GEN-LAST:event_addhabActionPerformed

    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        // Codigos necesarios para mostrar la subventana de productos en la interfaz
        addProducto producto = new addProducto();
        Ventana.add(producto);
        producto.show();
    }//GEN-LAST:event_addprodActionPerformed

    private void ResyproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResyproActionPerformed
        // Codigos necesarios para mostrar la subventana de reservaciones en la interfaz
        Reservacion reservacion = new Reservacion();
        Ventana.add(reservacion);
        reservacion.show();
    }//GEN-LAST:event_ResyproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CerrarP;
    private javax.swing.JMenuItem CerrarS;
    private javax.swing.JMenu Close;
    private javax.swing.JMenuItem Resypro;
    private javax.swing.JMenuItem Usu;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JPanel Ventana;
    private javax.swing.JMenuItem addcli;
    private javax.swing.JMenuItem addhab;
    private javax.swing.JMenuItem addprod;
    private javax.swing.JMenu menadd;
    private javax.swing.JMenu menres;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables
}
