import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
/*
*   VENTANA ENCARGADA DE INICIAR SESION EN EL PROGRAMA
*   INTEGRANTES DEL EQUIPO
*   - Kevin Alan Flores Reyna - 20660053
*   - Angel David Lopez Alvarez - 20660062
*/

public class Login extends javax.swing.JFrame implements Runnable {

    private static int trys = 5;        // Intentos de inicio de sesion antes de cerrar el programa 
    private static String rol = "";     // Rol del usuario que se ha logeado
    Thread dateTime;                    // Identificador del thread del metodo calcDateTime
    
    public Login() {
        initComponents();
        
        dateTime = new Thread(this);    // Se construye el thread
        dateTime.start();               // Se inicializa el thread
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descUsuario = new javax.swing.JLabel();
        txtRecId = new javax.swing.JTextField();
        descPass = new javax.swing.JLabel();
        txtPassRec = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tittle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(630, 420));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(630, 420));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 420));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descUsuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        descUsuario.setText("Codigo de Usuario:");
        jPanel1.add(descUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 130, -1));

        txtRecId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtRecId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, -1));

        descPass.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        descPass.setText("Contraseña:");
        jPanel1.add(descPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, -1));

        txtPassRec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPassRec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassRecKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 150, -1));

        btnLogin.setBackground(new java.awt.Color(194, 122, 15));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("INGRESAR");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 90, -1));

        tittle.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        tittle.setText("Iniciar Sesión");
        jPanel1.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTime.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 153, 0));
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 110, 20));

        txtDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 153, 0));
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 26, 110, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 120, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        icon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 240, 350));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Evento mandado a llamar siempre que se pulse el boton de acceso
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        tryLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPassRecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassRecKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            tryLogin();
        }
    }//GEN-LAST:event_txtPassRecKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Metodo derivado de la implementacion de Runnable
    public void run()
    {
        // Se instancia un nuevo thread
        Thread ct = Thread.currentThread();
        while(ct == dateTime)           // Se analiza si el thread es igual al constructor de dateTime
        {   
            calcDateTime();             // Se ejecuta el metodo calcDateTime para calcular la fecha
        try 
        {
            Thread.sleep(1000);         // El programa se espera 1 segundo en volver a ejecutarse
        }
        catch(InterruptedException e) {}
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel descPass;
    private javax.swing.JLabel descUsuario;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel tittle;
    private javax.swing.JLabel txtDate;
    private javax.swing.JPasswordField txtPassRec;
    private javax.swing.JTextField txtRecId;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables

    
    // Metodo loginCheck de tipo SDSR con parametros de usuario y contraseña
    private boolean loginCheck(String user, String pass) {
        PreparedStatement ps;           // Variable que se encarga de almacenar la sentencia de la consulta
        ResultSet rs;                   // Variable que se encarga de almacenar los resultados de la consulta
        boolean isExist = false;        // Valor que se regresara, por defecto tiene valor falso

        try {
            Conexion cx = new Conexion();                           // Se crea una nueva conexion
            Connection cn = cx.connect();                           // Se ejecuta el metodo connect() de la clase Conexion

            ps = cn.prepareStatement("CALL `LOGINrec`(?, ?)");      // Se prepara la linea de codigo para ejecutar el PROCEDURE
            ps.setString(1, user);                                  // Se asigna el valor del parametro user a la consulta
            ps.setString(2, pass);                                  // Se asigna el valor del parametro pass a la consulta

            rs = ps.executeQuery();                                 // Se ejecuta la consulta

            // Se comprueba si el valor arrojado de la consulta es diferente a nulo
            if(rs != null)
            {
                // Ciclo while donde se comprueba si existe un registro siguiente
                while(rs.next())
                {
                    // Se analiza el valor arrojado por la consulta
                    if(rs.getInt(1) == 1)
                    {
                        isExist = true;         // Si existen resultados de la consulta, se asigna el valor de verdadero
                    }
                    else
                    {
                        isExist = false;        // Si no existen resultados de la consulta, se asigna el valor de falso
                    }
                    rol = rs.getString("rolRec");
                }
            }
            cx.disconnect();    // Se cierra la conexion con la base de datos
        } 
        catch (SQLException ex) 
        {
            System.out.println("Error = " + ex);     // Se notifica via consola que ha ocurrido un error
        }
        return isExist;         // Se regresa el valor de la variable isExist
    }
    
    // Metodo calcDateTime para determinar la fecha y hora del dispositivo
    private void calcDateTime()
    {
        DateFormat timeFormat = new SimpleDateFormat("hh:mm:ss aa");            // Se establece un nuevo formato para la hora
        String time = timeFormat.format(Calendar.getInstance().getTime());      // Se instancia un nuevo objeto para obtener la fecha actual del dispositivo
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");             // Se establece un nuevo formato para la fecha, de forma en que se presenten los ultimos 2 digitos del año, el numero de mes y numero de dia
        String date = dateFormat.format(Calendar.getInstance().getTime());      // Se instancia un nuevo objeto para obtener la fecha actual del dispositivo
        
        // Se asigna la fecha y hora a los apartados necesarios
        txtTime.setText(time);
        txtDate.setText(date);
        
    }
    
    // Metodo tryLogin para realizar el ingreso al sistema
    private void tryLogin()
    {
        // Variables en las que se almacenaran lo almacenado en los espacios de la ventana
        String recID = txtRecId.getText();
        String passRec = txtPassRec.getText();
        
        // Se comprueba si los campos tienen valores nulos
        if(recID.equals("") || passRec.equals(""))
        {
            // Se lanza un mensaje de advertencia en caso de que se detecten los campos vacios
            JOptionPane.showMessageDialog(null, "Campos de Usuario y/o Contraseña vacios", "CAMPOS VACIOS", JOptionPane.WARNING_MESSAGE);
        }
        // Sin embargo, si no estan los campos vacios
        else
        {
            // Se comprueba el valor del metodo loginCheck en caso de que sea igual a verdadero
            if(loginCheck(recID,passRec))
            {
                JOptionPane.showMessageDialog(null, "BIENVENIDO","LOGIN EXITOSO", JOptionPane.INFORMATION_MESSAGE);
                new Interfaz(rol,recID).setVisible(true);         // Se instancia una nueva interfaz del menu principal
                this.dispose();                                   // La ventana actual (login) se cierra

            }
            // Sin embargo, si el valor es falso
            else
            {
                // Se resta 1 al valor actual de trys y se lanza un mensaje de error
                trys --;
                JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña incorrectos"+ 
                                                    "\nIntentos restantes = " + trys + ".","LOGIN FALLIDO", JOptionPane.ERROR_MESSAGE);

                // Se analiza si el valor actual de trys es igual o menor a 0
                if(trys <= 0)
                {
                    // Se notifica al usuario del cierre del programa
                    JOptionPane.showMessageDialog(null, "Intentos de inicio de sesion gastados", "CERRANDO PROGRAMA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);     // Se cierra el programa
                }
            }
        }
    }
}
