import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
*   VENTANA ENCARGADA PARA INICIAR SESION EN EL PROGRAMA
*   INTEGRANTES DEL EQUIPO
*   - Kevin Alan Flores Reyna - 20660053
*   - Angel David Lopez Alvarez - 20660062
*/


public class Login extends javax.swing.JFrame {

    private static int trys = 5;        // Intentos de inicio de sesion antes de cerrar el programa 
    
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setMaximumSize(new java.awt.Dimension(490, 463));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 60, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 80, -1));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 150, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icono-dorado-login-usuario.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setText("Iniciar Seción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Evento mandado a llamar siempre que se pulse el boton de acceso
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Variables en las que se almacenaran lo almacenado en los espacios de la ventana
        String recID = txtRecId.getText();
        String passRec = txtPassRec.getText();
        
        // Se comprueba si los campos tienen valores nulos
        if(recID.equals("") || passRec.equals(""))
        {
            // Se lanza un mensaje de advertencia en caso de que se detecten los campos vacios
            JOptionPane.showMessageDialog(null, "Campos de Usuario y/o Contraseña vacios", "CAMPOS VACIOS", JOptionPane.WARNING_MESSAGE);
        }
        // Sin embargo, si no estan los campos vacios
        else
        {
            // Se comprueba el valor del metodo loginCheck en caso de que sea igual a verdadero
            if(loginCheck(recID,passRec))
            {
                JOptionPane.showMessageDialog(null, "BIENVENIDO","LOGIN EXITOSO", JOptionPane.INFORMATION_MESSAGE);
                new Interfaz().setVisible(true);    // Se instancia una nueva interfaz del menu principal
                this.dispose();                     // La ventana actual (login) se cierra

            }
            // Sin embargo, si el valor es falso
            else
            {
                // Se resta 1 al valor actual de trys y se lanza un mensaje de error
                trys --;
                JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña incorrectos"+ 
                                                    "\nIntentos restantes = " + trys + ".","LOGIN FALLIDO", JOptionPane.ERROR_MESSAGE);

                // Se analiza si el valor actual de trys es igual o menor a 0
                if(trys <= 0)
                {
                    // Se notifica al usuario del cierre del programa
                    JOptionPane.showMessageDialog(null, "Intentos de inicio de sesion gastados", "CERRANDO PROGRAMA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);     // Se cierra el programa
                }
            }
        }
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel descPass;
    private javax.swing.JLabel descUsuario;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tittle;
    private javax.swing.JPasswordField txtPassRec;
    private javax.swing.JTextField txtRecId;
    // End of variables declaration     
    
    // Metodo loginCheck de tipo SDSR con parametros de usuario y contraseña
    private boolean loginCheck(String user, String pass) {
        PreparedStatement ps;           // Variable que se encarga de almacenar la sentencia de la consulta
        ResultSet rs;                   // Variable que se encarga de almacenar los resultados de la consulta
        boolean isExist = false;        // Valor que se regresara, por defecto tiene valor falso

        try {
            Conexion cx = new Conexion();                           // Se crea una nueva conexion
            Connection cn = cx.connect();                           // Se ejecuta el metodo connect() de la clase Conexion

            ps = cn.prepareStatement("CALL `SEARCHrec`(?, ?)");     // Se prepara la linea de codigo para ejecutar el PROCEDURE
            ps.setString(1, user);                                  // Se asigna el valor del parametro user a la consulta
            ps.setString(2, pass);                                  // Se asigna el valor del parametro pass a la consulta

            rs = ps.executeQuery();                                 // Se ejecuta la consulta

            // Se comprueba si el valor arrojado de la consulta es diferente a nulo
            if(rs != null)
            {
                // Ciclo while donde se comprueba si existe un registro siguiente
                while(rs.next())
                {
                    // Se analiza el valor arrojado por la consulta
                    if(rs.getInt(1) == 1)
                    {
                        isExist = true;         // Si existen resultados de la consulta, se asigna el valor de verdadero
                    }
                    else
                    {
                        isExist = false;        // Si no existen resultados de la consulta, se asigna el valor de falso
                    }
                }
            }
        } 
        catch (SQLException ex) 
        {
            System.out.println("Error = " + ex);     // Se notifica via consola que ha ocurrido un error
        }
        return isExist;         // Se regresa el valor de la variable isExist
    }
}
